# Model Selection and Shrinkage Methods

Created on 2026-10-05

@author: Ruowen Xiao

## Training

In [8]:
import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.linear_model import RidgeCV
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [ ]:
# import data
file_path_train = "./data/sleep_train.csv"
df_train = pd.read_csv(file_path_train)
df_train.head()

,ID,Gender,Age,Occupation,Physical_Activity_Level,Stress_Level,BMI_Category,Heart_Rate,Daily_Steps,Sleep_Disorder,Temp,Mood,History,Quality_of_Sleep,Sleep_Duration
0,311,Female,49,Nurse,90,8,Overweight,75,10000,Sleep Apnea,-1.278341,0.440786,5.407088,7.474116,6.2
1,207,Male,30,Doctor,75,6,Normal,70,8000,NaN,-0.826910,0.691399,5.839617,7.979600,7.7
2,169,Male,35,Engineer,60,4,Normal,65,5000,NaN,1.139555,0.909316,7.039570,5.902686,7.3
3,149,Male,39,Lawyer,60,5,Normal,68,8000,NaN,2.069801,0.741677,4.464130,8.127826,7.2
4,98,Female,50,Nurse,90,8,Overweight,75,10000,Sleep Apnea,-2.907425,0.418233,3.068291,8.099139,6.0

In [9]:
X_train = df_train.drop(columns=["ID", "Sleep_Duration"])
y_train = df_train["Sleep_Duration"]

In [7]:
numerical_features = [
    "Age",
    "Physical_Activity_Level",
    "Stress_Level",
    "Heart_Rate",
    "Daily_Steps",
    "Temp",
    "Mood",
    "History",
    "Quality_of_Sleep"
]

categorical_features = [
    "Gender",
    "Occupation",
    "BMI_Category",
    "Sleep_Disorder"
]

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

In [12]:
alphas = np.array([0.01, 0.1, 1.0, 10.0, 100.0])

model = make_pipeline(
    preprocessor,
    RidgeCV(
        alphas=alphas,
        cv=5
    )
)

model.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Age',
                                                   'Physical_Activity_Level',
                                                   'Stress_Level', 'Heart_Rate',
                                                   'Daily_Steps', 'Temp',
                                                   'Mood', 'History',
                                                   'Quality_of_Sleep']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['Gender', 'Occupation',
                                                   'BMI_Category',
                                                   'Sleep_Disorder'])])),
                ('ridgecv',
                 RidgeCV(alphas=array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         cv=5))])

## Prediction

In [4]:
# import data
file_path_test = "./data/sleep_test.csv"
df_test = pd.read_csv(file_path_test)
df_test.head()

,ID,Gender,Age,Occupation,Physical_Activity_Level,Stress_Level,BMI_Category,Heart_Rate,Daily_Steps,Sleep_Disorder,Temp,Mood,History,Quality_of_Sleep
0,3,Male,31,Doctor,30,8,Normal,72,5000,NaN,-1.627562,0.474605,6.029331,5.970977
1,234,Male,43,Salesperson,45,7,Overweight,72,6000,Sleep Apnea,3.311945,0.567641,5.366240,5.824984
2,187,Female,44,Teacher,45,4,Overweight,65,6000,Insomnia,0.800264,0.924036,6.645139,7.465405
3,220,Male,33,Doctor,30,8,Normal,72,5000,NaN,4.397880,0.512827,8.466199,7.946357
4,106,Male,30,Doctor,75,6,Normal,70,8000,NaN,-0.383691,0.634333,6.751696,6.343607

In [16]:
X_test = df_test.drop(columns=["ID"])

y_pred = model.predict(X_test)

In [ ]:
df_pred = pd.DataFrame({
    "ID": df_test["ID"],
    "Sleep_Duration": y_pred
})

df_pred.head()

    ID  Sleep_Duration
0    3        6.498264
1  234        6.404290
2  187        6.870058
3  220        6.645279
4  106        7.280792

In [20]:
file_path_pred = "./data/sleep_pred.csv"
df_pred.to_csv(file_path_pred, index=False)